# System Configuration

network_interface: "eth0"
log_file_path: "data/logs/system.log"

filter:
  source_ip: ""
  destination_ip: ""
  protocol: ""
  port: ""
  bpf: ""  # Example: "tcp and port 80"

incident_response:
  HighPacketSizeDetected: "sh -c 'echo \"High packet size detected\" | mail -s \"Network Alert\" admin@example.com'"

authentication:
  username: "admin"
  password: "password"